// Generated by the portfolio editor. Replace this project's site-data.js with this file when publishing.
window.PORTFOLIO_PUBLISHED_DATA = {
  "appearance": {
    "tone": "warm",
    "accent": "forest",
    "density": "spacious"
  },
  "categories": [
    "Personal Project"
  ],
  "profile": {
    "name": "KYLE YINGJIE",
    "role": "Visual Designer & 2D Artist",
    "statement": "Visual and UI design for digital games.",
    "about": "Detail-oriented, adaptable, and collaborative visual designer with experience creating visual and UI content for digital games.",
    "email": "kyleyingjie@gmail.com",
    "phone": "+65 8612 3313",
    "instagram": "",
    "linkedin": "",
    "cvUrl": "assets/Kyle_Yingjie_Resume_2026.pdf",
    "cvLabel": "Download CV (PDF)"
  },
  "experience": [
    {
      "years": "Aug 2020 - Mar 2026",
      "role": "2D Artist",
      "place": "Dynamite Games, Singapore",
      "summary": "Created characters, environments, backgrounds, visual effects, UI, and menus for more than 10 launched mobile games."
    },
    {
      "years": "Jun - Jul 2021",
      "role": "Freelance Visual Designer",
      "place": "Iterative Collective, Singapore",
      "summary": "Led visual development for Kungfu Dash, covering character design, art direction, animation, and UI/UX."
    },
    {
      "years": "Aug 2019 - Aug 2020",
      "role": "Digital Artist",
      "place": "Digital Mirage, Singapore",
      "summary": "Produced photorealistic client visuals from 3D renders through matte painting, digital imaging, and color grading."
    }
  ],
  "education": [
    {
      "years": "Jul 2017 - May 2019",
      "role": "Bachelor of Arts (Animation Art)",
      "place": "LASALLE College of the Arts, Singapore - Second Class Honours (Upper Division)"
    },
    {
      "years": "2011 - 2012",
      "role": "A-Levels",
      "place": "Catholic Junior College, Singapore"
    }
  ],
  "skills": [
    "Illustration",
    "UI Design",
    "Adobe Photoshop",
    "Midjourney",
    "Stable Diffusion",
    "Runway"
  ],
  "recognition": [
    "National Youth Film Award 2020 - Best Art Direction (Individual)",
    "Crowbar 2019 - Art Direction Gold, Animation Gold, Editing Silver, Cinematography Bronze (Team)",
    "Cartoons Underground 2019 - Audience Choice and Special Mention (Team)",
    "DigiCon6 Asia 2018 - Next Generation Award (Team)",
    "Crowbar 2018 - Cinematography Silver Award (Team)",
    "Crowbar 2018 - Animation Silver Award (Team)",
    "Crowbar 2018 - Effects Bronze Award (Team)"
  ],
  "artworks": [
    {
      "id": "for-fun-challenge",
      "title": "MLBB Challenge",
      "category": "Personal Project",
      "aspect": "landscape",
      "images": [
        "assets/projects/for-fun-challenge/001_sketches_for_full-team.jpg",
        "assets/projects/for-fun-challenge/002sketches_for_team-indi_start.jpg",
        "assets/projects/for-fun-challenge/003_sketches_for_team-indi_yve.jpg",
        "assets/projects/for-fun-challenge/004sketches_for_team-indi_natan.jpg",
        "assets/projects/for-fun-challenge/005sketches_for_team-indi_balmond.jpg",
        "assets/projects/for-fun-challenge/005sketches_for_team-indi_uranus.jpg",
        "assets/projects/for-fun-challenge/006sketches_for_team-indi_franco.jpg",
        "assets/projects/for-fun-challenge/007sketches_thumbnails_yve.jpg",
        "assets/projects/for-fun-challenge/008sketches_thumbnails_natan.jpg",
        "assets/projects/for-fun-challenge/009sketches_thumbnails_balmond.jpg",
        "assets/projects/for-fun-challenge/010sketches_thumbnails_uranus.jpg",
        "assets/projects/for-fun-challenge/011sketches_thumbnails_franco.jpg",
        "assets/projects/for-fun-challenge/012sketches_for_yve.jpg",
        "assets/projects/for-fun-challenge/013sketches_for_natan.jpg",
        "assets/projects/for-fun-challenge/014sketches_for_balmond.jpg",
        "assets/projects/for-fun-challenge/015sketches_for_uranus.jpg",
        "assets/projects/for-fun-challenge/016sketches_for_franco.jpg"
      ],
      "image": ""
    }
  ]
};
