// Generated by the portfolio editor. Replace this project's site-data.js with this file when publishing.
window.PORTFOLIO_PUBLISHED_DATA = {
  "appearance": {
    "tone": "warm",
    "accent": "forest",
    "density": "spacious"
  },
  "categories": [
    "Personal Project"
  ],
  "profile": {
    "name": "Hi, I am Kyle Yingjie!",
    "role": "Visual Designer & 2D Artist",
    "statement": "Visual and UI design for digital games.",
    "about": "Detail-oriented, adaptable, and collaborative visual designer with experience creating visual and UI content for digital games.",
    "email": "kyleyingjie@gmail.com",
    "phone": "+65 8612 3313",
    "instagram": "",
    "linkedin": "",
    "cvUrl": "assets/Kyle_Yingjie_Resume_2026.pdf",
    "cvLabel": "Download CV (PDF)"
  },
  "experience": [
    {
      "years": "Aug 2020 - Mar 2026",
      "role": "2D Artist",
      "place": "Dynamite Games, Singapore",
      "summary": "Created characters, environments, backgrounds, visual effects, UI, and menus for more than 10 launched mobile games."
    },
    {
      "years": "Jun - Jul 2021",
      "role": "Freelance Visual Designer",
      "place": "Iterative Collective, Singapore",
      "summary": "Led visual development for Kungfu Dash, covering character design, art direction, animation, and UI/UX."
    },
    {
      "years": "Aug 2019 - Aug 2020",
      "role": "Digital Artist",
      "place": "Digital Mirage, Singapore",
      "summary": "Produced photorealistic client visuals from 3D renders through matte painting, digital imaging, and color grading."
    }
  ],
  "education": [
    {
      "years": "Jul 2017 - May 2019",
      "role": "Bachelor of Arts (Animation Art)",
      "place": "LASALLE College of the Arts, Singapore - Second Class Honours (Upper Division)"
    }
  ],
  "skills": [
    "Illustration",
    "UI Design",
    "Adobe Photoshop",
    "Blender",
    "ZBrush",
    "Midjourney",
    "Stable Diffusion",
    "Runway"
  ],
  "recognition": [
    "National Youth Film Award 2020 - Best Art Direction (Individual)",
    "Crowbar 2019 - Art Direction Gold, Animation Gold, Editing Silver, Cinematography Bronze (Team)",
    "Cartoons Underground 2019 - Audience Choice and Special Mention (Team)",
    "DigiCon6 Asia 2018 - Next Generation Award (Team)",
    "Crowbar 2018 - Cinematography Silver Award (Team)",
    "Crowbar 2018 - Animation Silver Award (Team)",
    "Crowbar 2018 - Effects Bronze Award (Team)"
  ],
  "aiFilms": [],
  "artworks": [
    {
      "id": "for-fun-challenge",
      "title": "MLBB Challenge",
      "category": "Personal Project",
      "aspect": "landscape",
      "images": [
        "assets/projects/for-fun-challenge/sketches_for_ipad-5.jpg",
        "assets/projects/for-fun-challenge/001_sketches_for_full-team.jpg",
        "assets/projects/for-fun-challenge/002sketches_for_team-indi_start.jpg",
        "assets/projects/for-fun-challenge/003_sketches_for_team-indi_yve.jpg",
        "assets/projects/for-fun-challenge/004sketches_for_team-indi_natan.jpg",
        "assets/projects/for-fun-challenge/005sketches_for_team-indi_balmond.jpg",
        "assets/projects/for-fun-challenge/005sketches_for_team-indi_uranus.jpg",
        "assets/projects/for-fun-challenge/006sketches_for_team-indi_franco.jpg",
        "assets/projects/for-fun-challenge/007sketches_thumbnails_yve.jpg",
        "assets/projects/for-fun-challenge/008sketches_thumbnails_natan.jpg",
        "assets/projects/for-fun-challenge/009sketches_thumbnails_balmond.jpg",
        "assets/projects/for-fun-challenge/010sketches_thumbnails_uranus.jpg",
        "assets/projects/for-fun-challenge/011sketches_thumbnails_franco.jpg",
        "assets/projects/for-fun-challenge/012sketches_for_yve.jpg",
        "assets/projects/for-fun-challenge/013sketches_for_natan.jpg",
        "assets/projects/for-fun-challenge/014sketches_for_balmond.jpg",
        "assets/projects/for-fun-challenge/015sketches_for_uranus.jpg",
        "assets/projects/for-fun-challenge/016sketches_for_franco.jpg"
      ],
      "image": "assets/projects/for-fun-challenge/sketches_for_ipad-5.jpg"
    },
    {
      "id": "elf-forager",
      "title": "Stylized Prop Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/elf-forager/elf-forager_03.jpg",
      "images": [
        "assets/projects/elf-forager/elf-forager_01.jpg",
        "assets/projects/elf-forager/elf-forager_02.jpg",
        "assets/projects/elf-forager/elf-forager_03.jpg",
        "assets/projects/elf-forager/elf-forager_04.jpg",
        "assets/projects/elf-forager/elf-forager_05.jpg",
        "assets/projects/elf-forager/elf-pots_01.jpg"
      ]
    },
    {
      "id": "survivor-pack",
      "title": "Survivor Pack - Art Test",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/survivor-pack/Art-test_KyleYingjie_02.jpg",
      "images": [
        "assets/projects/survivor-pack/Art-test_KyleYingjie.jpg",
        "assets/projects/survivor-pack/Art-test_KyleYingjie_01.jpg",
        "assets/projects/survivor-pack/Art-test_KyleYingjie_02.jpg",
        "assets/projects/survivor-pack/art-test-02_02.jpg"
      ]
    },
    {
      "id": "giant-armor-glove",
      "title": "Giant Armor Glove Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/giant-armor-glove/Giant_armor_glove_design_02.jpg",
      "images": [
        "assets/projects/giant-armor-glove/Giant_armor_glove_design_00asfa1.jpg",
        "assets/projects/giant-armor-glove/Giant_armor_glove_design_00fsaf1.jpg",
        "assets/projects/giant-armor-glove/Giant_armor_glove_design_02.jpg",
        "assets/projects/giant-armor-glove/Giant_armor_glove_design_03.jpg",
        "assets/projects/giant-armor-glove/Character_design_with_oversized_gauntlet.jpg",
        "assets/projects/giant-armor-glove/Giant_armor_glove_design_05.jpg"
      ]
    },
    {
      "id": "klaus-environment",
      "title": "Klaus Environment Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/klaus-environment/Group 4.jpg",
      "images": [
        "assets/projects/klaus-environment/Klaus_animated_film_environment_001.jpg",
        "assets/projects/klaus-environment/Group 4.jpg",
        "assets/projects/klaus-environment/Group 2.jpg",
        "assets/projects/klaus-environment/Group 3.jpg",
        "assets/projects/klaus-environment/Klaus_animated_film_environment_005.jpg"
      ]
    },
    {
      "id": "infold-merch",
      "title": "Infold Merch Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/infold-merch/Group 8.jpg",
      "images": [
        "assets/projects/infold-merch/Group 7.jpg",
        "assets/projects/infold-merch/Group 8.jpg",
        "assets/projects/infold-merch/Group 9dsg.jpg",
        "assets/projects/infold-merch/infold_merch_0gsdgsd1.jpg",
        "assets/projects/infold-merch/infold_merch_01.jpg",
        "assets/projects/infold-merch/infold.jpeg"
      ]
    },
    {
      "id": "professional-portfolio",
      "title": "Professional Portfolio",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/professional-portfolio/professional-portfolio-01.jpg",
      "images": [
        "assets/projects/professional-portfolio/professional-portfolio-01.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-02.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-03.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-04.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-05.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-06.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-07.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-08.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-09.jpg"
      ]
    },
    {
      "id": "game-ui-design",
      "title": "Game UI Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/game-ui-design/UI - Dungeon Sweeper1.jpg",
      "images": [
        "assets/projects/game-ui-design/UI - Dungeon Sweeper1.jpg",
        "assets/projects/game-ui-design/UI - Casino1.jpg",
        "assets/projects/game-ui-design/UI - Jackpot1.jpg",
        "assets/projects/game-ui-design/SG60_03.jpg",
        "assets/projects/game-ui-design/UI - Kungfu Dash 1.jpg",
        "assets/projects/game-ui-design/UI - Kungfu Dash 2.jpg",
        "assets/projects/game-ui-design/UI - Pirate1.jpg",
        "assets/projects/game-ui-design/UI - Project Ricochet 1.jpg",
        "assets/projects/game-ui-design/UI - Project Ricochet 2.jpg",
        "assets/projects/game-ui-design/cargostudioshowcase.jpg",
        "assets/projects/game-ui-design/UI - Shop01.jpg",
        "assets/projects/game-ui-design/Vytha-shop-illustration_0saf.jpg"
      ]
    },
    {
      "id": "dungeon-sweeper",
      "title": "Dungeon Sweeper",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/dungeon-sweeper/Toon_soldier_001.jpg",
      "images": [
        "assets/projects/dungeon-sweeper/Toon_soldier_001.jpg",
        "assets/projects/dungeon-sweeper/Toon_soldier_001nologo.jpg",
        "assets/projects/dungeon-sweeper/minesweeper-illust_01c.jpg",
        "assets/projects/dungeon-sweeper/Lighting_conditions_for_game_art.jpg",
        "assets/projects/dungeon-sweeper/minesweeper-illust_02.jpg",
        "assets/projects/dungeon-sweeper/minesweeper-illust_02sd.jpg",
        "assets/projects/dungeon-sweeper/Generating.jpg",
        "assets/projects/dungeon-sweeper/minesweeper-logo_01bd.jpg",
        "assets/projects/dungeon-sweeper/UI - DungeonSweeper1.jpg"
      ]
    },
    {
      "id": "fan-art",
      "title": "Fan Art",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/fan-art/Elf_in_forest_splash_art_001.jpg",
      "images": [
        "assets/projects/fan-art/splash 0111.jpg",
        "assets/projects/fan-art/splash 0222.jpg",
        "assets/projects/fan-art/Akali_mid_air_002.jpg",
        "assets/projects/fan-art/viego.jpg",
        "assets/projects/fan-art/CLASS02b copy3.jpg",
        "assets/projects/fan-art/Elf_in_forest_splash_art_001.jpg",
        "assets/projects/fan-art/bust.jpeg",
        "assets/projects/fan-art/bust_painting_001.jpg"
      ]
    },
    {
      "id": "creature-design",
      "title": "Creature Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/creature-design/Character 2 - Copy.jpg",
      "images": [
        "assets/projects/creature-design/Character 2.jpg",
        "assets/projects/creature-design/Character 3.jpg",
        "assets/projects/creature-design/Character 4a.jpg",
        "assets/projects/creature-design/Character 4b.jpg",
        "assets/projects/creature-design/Character 10.jpg",
        "assets/projects/creature-design/Character 2 - Copy.jpg"
      ]
    }
  ]
};
