// Generated by the portfolio editor. Replace this project's site-data.js with this file when publishing.
window.PORTFOLIO_PUBLISHED_DATA = {
  "appearance": {
    "tone": "warm",
    "accent": "forest",
    "density": "spacious"
  },
  "categories": [
    "Personal Project"
  ],
  "profile": {
    "name": "Hi, I am Kyle Ying Jie!",
    "role": "Visual Designer & 2D Artist",
    "statement": "Visual and UI design for digital games.",
    "about": "Detail-oriented, adaptable, and collaborative visual designer with experience creating visual and UI content for digital games.",
    "email": "kyleyingjie@gmail.com",
    "phone": "+65 8612 3313",
    "instagram": "",
    "linkedin": "",
    "cvUrl": "assets/Kyle_Ying_Jie_Resume_2026.pdf",
    "cvLabel": "Download CV (PDF)"
  },
  "experience": [
    {
      "years": "Aug 2020 - Mar 2026",
      "role": "2D Artist",
      "place": "Dynamite Games, Singapore",
      "summary": "Created characters, environments, backgrounds, visual effects, UI, and menus for more than 10 launched mobile games."
    },
    {
      "years": "Jun - Jul 2021",
      "role": "Freelance Visual Designer",
      "place": "Iterative Collective, Singapore",
      "summary": "Led visual development for Kungfu Dash, covering character design, art direction, animation, and UI/UX."
    },
    {
      "years": "Aug 2019 - Aug 2020",
      "role": "Digital Artist",
      "place": "Digital Mirage, Singapore",
      "summary": "Produced photorealistic client visuals from 3D renders through matte painting, digital imaging, and color grading."
    }
  ],
  "education": [
    {
      "years": "Jul 2017 - May 2019",
      "role": "Bachelor of Arts (Animation Art)",
      "place": "LASALLE College of the Arts, Singapore - Second Class Honours (Upper Division)"
    }
  ],
  "skills": [
    "Illustration",
    "UI Design",
    "Adobe Photoshop",
    "Blender",
    "ZBrush",
    "Midjourney",
    "Stable Diffusion",
    "Runway"
  ],
  "recognition": [
    "National Youth Film Award 2020 - Best Art Direction (Individual)",
    "Crowbar 2019 - Art Direction Gold, Animation Gold, Editing Silver, Cinematography Bronze (Team)",
    "Cartoons Underground 2019 - Audience Choice and Special Mention (Team)",
    "DigiCon6 Asia 2018 - Next Generation Award (Team)",
    "Crowbar 2018 - Cinematography Silver Award (Team)",
    "Crowbar 2018 - Animation Silver Award (Team)",
    "Crowbar 2018 - Effects Bronze Award (Team)"
  ],
  "aiFilms": [],
  "artworks": [
    {
      "id": "for-fun-challenge",
      "title": "MLBB Challenge",
      "category": "Personal Project",
      "aspect": "landscape",
      "images": [
        "assets/projects/for-fun-challenge/for-fun-challenge-01.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-02.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-03.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-04.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-05.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-06.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-07.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-08.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-09.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-10.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-11.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-12.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-13.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-14.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-15.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-16.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-17.jpg",
        "assets/projects/for-fun-challenge/for-fun-challenge-18.jpg"
      ],
      "image": "assets/projects/for-fun-challenge/for-fun-challenge-01.jpg"
    },
    {
      "id": "elf-forager",
      "title": "Stylized Prop Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/elf-forager/elf-forager-03.jpg",
      "images": [
        "assets/projects/elf-forager/elf-forager-01.jpg",
        "assets/projects/elf-forager/elf-forager-02.jpg",
        "assets/projects/elf-forager/elf-forager-03.jpg",
        "assets/projects/elf-forager/elf-forager-04.jpg",
        "assets/projects/elf-forager/elf-forager-05.jpg",
        "assets/projects/elf-forager/elf-forager-06.jpg"
      ]
    },
    {
      "id": "survivor-pack",
      "title": "Survivor Pack - Art Test",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/survivor-pack/survivor-pack-03.jpg",
      "images": [
        "assets/projects/survivor-pack/survivor-pack-01.jpg",
        "assets/projects/survivor-pack/survivor-pack-02.jpg",
        "assets/projects/survivor-pack/survivor-pack-03.jpg",
        "assets/projects/survivor-pack/survivor-pack-04.jpg"
      ]
    },
    {
      "id": "giant-armor-glove",
      "title": "Giant Armor Glove Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/giant-armor-glove/giant-armor-glove-04.jpg",
      "images": [
        "assets/projects/giant-armor-glove/giant-armor-glove-01.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-02.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-03.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-04.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-05.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-06.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-07.jpg",
        "assets/projects/giant-armor-glove/giant-armor-glove-08.jpg"
      ]
    },
    {
      "id": "klaus-environment",
      "title": "Klaus Environment Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/klaus-environment/klaus-environment-02.jpg",
      "images": [
        "assets/projects/klaus-environment/klaus-environment-01.jpg",
        "assets/projects/klaus-environment/klaus-environment-02.jpg",
        "assets/projects/klaus-environment/klaus-environment-03.jpg",
        "assets/projects/klaus-environment/klaus-environment-04.jpg",
        "assets/projects/klaus-environment/klaus-environment-05.jpg"
      ]
    },
    {
      "id": "infold-merch",
      "title": "Infold Merch Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/infold-merch/infold-merch-02.jpg",
      "images": [
        "assets/projects/infold-merch/infold-merch-01.jpg",
        "assets/projects/infold-merch/infold-merch-02.jpg",
        "assets/projects/infold-merch/infold-merch-03.jpg",
        "assets/projects/infold-merch/infold-merch-04.jpg",
        "assets/projects/infold-merch/infold-merch-05.jpg",
        "assets/projects/infold-merch/infold-merch-06.jpeg"
      ]
    },
    {
      "id": "professional-portfolio",
      "title": "Professional Works",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/professional-portfolio/professional-portfolio-02.jpg",
      "images": [
        "assets/projects/professional-portfolio/professional-portfolio-02.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-03.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-04.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-05.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-06.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-07.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-08.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-09.jpg",
        "assets/projects/professional-portfolio/professional-portfolio-10.jpg"
      ]
    },
    {
      "id": "game-ui-design",
      "title": "Game UI Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/game-ui-design/game-ui-design-01.jpg",
      "images": [
        "assets/projects/game-ui-design/game-ui-design-01.jpg",
        "assets/projects/game-ui-design/game-ui-design-02.jpg",
        "assets/projects/game-ui-design/game-ui-design-03.jpg",
        "assets/projects/game-ui-design/game-ui-design-04.jpg",
        "assets/projects/game-ui-design/game-ui-design-05.jpg",
        "assets/projects/game-ui-design/game-ui-design-06.jpg",
        "assets/projects/game-ui-design/game-ui-design-07.jpg",
        "assets/projects/game-ui-design/game-ui-design-08.jpg",
        "assets/projects/game-ui-design/game-ui-design-09.jpg",
        "assets/projects/game-ui-design/game-ui-design-10.jpg",
        "assets/projects/game-ui-design/game-ui-design-11.jpg",
        "assets/projects/game-ui-design/game-ui-design-12.jpg",
        "assets/projects/game-ui-design/game-ui-design-13.jpg"
      ]
    },
    {
      "id": "dungeon-sweeper",
      "title": "Dungeon Sweeper",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/dungeon-sweeper/dungeon-sweeper-01.jpg",
      "images": [
        "assets/projects/dungeon-sweeper/dungeon-sweeper-01.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-02.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-03.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-04.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-05.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-06.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-07.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-08.jpg",
        "assets/projects/dungeon-sweeper/dungeon-sweeper-09.jpg"
      ]
    },
    {
      "id": "fan-art",
      "title": "Fan Art",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/fan-art/fan-art-07.jpg",
      "images": [
        "assets/projects/fan-art/fan-art-01.jpg",
        "assets/projects/fan-art/fan-art-02.jpg",
        "assets/projects/fan-art/fan-art-03-akali.jpg",
        "assets/projects/fan-art/fan-art-04.jpg",
        "assets/projects/fan-art/fan-art-05.jpg",
        "assets/projects/fan-art/fan-art-06.jpg",
        "assets/projects/fan-art/fan-art-07.jpg",
        "assets/projects/fan-art/fan-art-08.jpeg",
        "assets/projects/fan-art/fan-art-09.jpg"
      ]
    },
    {
      "id": "creature-design",
      "title": "Creature Design",
      "category": "Personal Project",
      "aspect": "landscape",
      "image": "assets/projects/creature-design/creature-design-08.jpg",
      "images": [
        "assets/projects/creature-design/creature-design-08.jpg",
        "assets/projects/creature-design/creature-design-01.jpg",
        "assets/projects/creature-design/creature-design-02.jpg",
        "assets/projects/creature-design/creature-design-03.jpg",
        "assets/projects/creature-design/creature-design-04.jpg",
        "assets/projects/creature-design/creature-design-05.jpg",
        "assets/projects/creature-design/creature-design-06.jpg",
        "assets/projects/creature-design/creature-design-07.jpg",
        "assets/projects/creature-design/creature-design-10.jpg",
        "assets/projects/creature-design/creature-design-09.jpg"
      ]
    },
    {
      "id": "wind-character-design",
      "title": "Wind Ninja Design",
      "category": "Personal Project",
      "aspect": "portrait",
      "image": "assets/projects/wind-character-design/wind-character-design-01.jpg",
      "images": [
        "assets/projects/wind-character-design/wind-character-design-01.jpg",
        "assets/projects/wind-character-design/wind-character-design-02.jpg",
        "assets/projects/wind-character-design/wind-character-design-06.jpg",
        "assets/projects/wind-character-design/wind-character-design-03.jpg",
        "assets/projects/wind-character-design/wind-character-design-04.jpg",
        "assets/projects/wind-character-design/wind-character-design-05.jpg"
      ]
    }
  ]
};
